export const OPENING_PROMPTS = [
  "How has your day been?",
  "What's been keeping you busy lately?",
  "What have you been up to recently?",
  "What are you looking forward to these days?",
  "What have you been enjoying lately?",
  "What is something you've been thinking about recently?",
  "What do you usually like doing after work or college?",
  "What kind of things do you enjoy talking about?",
  "What's something you could talk about for hours?",
  "What have you been learning recently?",
  "What's something new you've tried lately?",
  "What is something you're excited about right now?",
  "What's been going well for you recently?",
  "What's something that made you smile recently?",
  "What does a typical day look like for you?",
  "What do you usually do on weekends?",
  "What's your favorite way to spend a free evening?",
  "What kind of music, movies, or shows do you enjoy?",
  "What's a place you've really enjoyed visiting?",
  "Tell me something interesting about where you live.",
  "If you could take a short trip tomorrow, where would you go?",
  "What's something you wish you had more time for?",
  "What are you currently working on?",
  "What's something you're trying to get better at?",
  "What's something you've been curious about lately?",
  "What's one thing you've enjoyed recently that you'd recommend?",
  "What is something you're looking forward to this month?",
  "What's something that has been on your mind lately?",
];

export const FOLLOW_UPS = [
  "Tell me more about that.",
  "What was that like?",
  "How did that happen?",
  "How did you get into it?",
  "What made you interested in that?",
  "What do you enjoy most about it?",
  "What do you like about it?",
  "What happened next?",
  "How did you feel about that?",
  "What was the best part?",
  "Was that something you always wanted to do?",
  "What surprised you about it?",
  "What was that experience like?",
  "How did you get started?",
  "What made you choose that?",
  "What do you usually do?",
  "How often do you do that?",
  "Is that something you really enjoy?",
  "What would you like to do next?",
  "Would you do it again?",
  "What makes it interesting to you?",
  "Has that always been the case?",
  "What do you mean by that?",
  "Can you give me an example?",
  "What was the most interesting part?",
];

export const SESSION_LENGTH_SECONDS = 10 * 60;
